drop alias HATBOX_SPATIALIZE;

drop alias HATBOX_BUILD_INDEX;

drop alias HATBOX_DE_SPATIALIZE;

drop alias HATBOX_MBR_INTERSECTS_ENV;

drop alias HATBOX_INTERSECTS_WKB;

drop alias HATBOX_INTERSECTS_WKT;

drop alias HATBOX_QUERY_WITH_PREDICATE_WKB;

drop alias HATBOX_QUERY_WITH_PREDICATE_WKT;

drop alias HATBOX_GET_DATASET_BOUNDS;