drop procedure HATBOX.SPATIALIZE_PROC;

drop procedure HATBOX.BUILD_INDEX_PROC;

drop procedure HATBOX.DE_SPATIALIZE_PROC;

drop procedure HATBOX.INS_SPATIAL_PROC;

drop procedure HATBOX.UPD_SPATIAL_PROC;

drop procedure HATBOX.DEL_SPATIAL_PROC;

drop procedure HATBOX.SAVE_ENTRY_PROC;

drop function HATBOX.MBR_INTERSECTS_ENV;

drop function HATBOX.INTERSECTS_WKB;

drop function HATBOX.INTERSECTS_WKT;

drop function HATBOX.QUERY_WITH_PREDICATE_WKB;

drop function HATBOX.QUERY_WITH_PREDICATE_WKT;
