package geoscript.carto.io

import geoscript.carto.CartoBuilder
import org.junit.jupiter.api.Test
import static org.junit.jupiter.api.Assertions.assertEquals

class XmlCartoReaderTest {

    @Test void getName() {
        CartoReader cartoReader = new XmlCartoReader()
        assertEquals("xml", cartoReader.name)
    }

    @Test void readCarto() {
        String xml = """<carto>
          <type>png</type>
          <width>792</width>
          <height>612</height>
          <items>
            <item>
                <x>0</x>
                <y>0</y>
                <width>792</width>
                <height>612</height>
                <type>rectangle</type>
                <fillColor>white</fillColor>
                <strokeColor>white</strokeColor>
            </item>
            <item>
                <x>0</x>
                <y>0</y>
                <width>792</width>
                <height>612</height>
                <type>grid</type>
                <size>10</size>
                <strokeColor>black</strokeColor>
                <strokeWidth>1</strokeWidth>
            </item>
            <item>
                <x>10</x>
                <y>10</y>
                <width>772</width>
                <height>592</height>
                <type>rectangle</type>
                <strokeWidth>1.0</strokeWidth>
                <strokeColor>black</strokeColor>
                <fillColor>white</fillColor>
                <strokeWidth>1</strokeWidth>
            </item>
            <item>
                <x>20</x>
                <y>20</y>
                <width>752</width>
                <height>80</height>
                <type>rectangle</type>
            </item>
            <item>
                <x>30</x>
                <y>50</y>
                <width>200</width>
                <height>20</height>
                <type>text</type>
                <text>Map Title</text>
                <font>
                    <name>Arial</name>
                    <style>Bold</style>
                    <size>36</size>
                </font>
                <color>black</color>
                <horizontalAlign>left</horizontalAlign>
                <verticalAlign>bottom</verticalAlign>
            </item>
            <item>
                <x>30</x>
                <y>85</y>
                <width>200</width>
                <height>10</height>
                <type>dateText</type>
                <format>MM/dd/yyyy</format>
                <date>12/29/2020</date>
                <color>black</color>
                <horizontalAlign>left</horizontalAlign>
                <verticalAlign>bottom</verticalAlign>
                <font>
                    <name>Arial</name>
                    <style>Italic</style>
                    <size>18</size>
                </font>
            </item>
            <item>
                <x>250</x>
                <y>30</y>
                <width>380</width>
                <height>70</height>
                <type>paragraph</type>
                <text>Permission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the Software), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\nThe above copyright notice and this permission notice shall be included in\nall copies or substantial portions of the Software.</text>
                <font>
                    <name>Arial</name>
                    <style>Plain</style>
                    <size>8</size>
                </font>
                <color>black</color>
            </item>
            <item>
                <x>710</x>
                <y>30</y>
                <width>1</width>
                <height>60</height>
                <type>line</type>
                <strokeColor>black</strokeColor>
                <strokeWidth>1</strokeWidth>
            </item>
            <item>
                <x>640</x>
                <y>30</y>
                <width>60</width>
                <height>60</height>
                <type>image</type>
                <path>${new File(getClass().getClassLoader().getResource("image.png").toURI()).absolutePath}</path>
            </item>
            <item>
                <x>720</x>
                <y>30</y>
                <width>40</width>
                <height>60</height>
                <type>northArrow</type>
                <fillColor1>black</fillColor1>
                <strokeColor1>black</strokeColor1>
                <fillColor2>white</fillColor2>
                <strokeColor2>black</strokeColor2>
                <strokeWidth>1</strokeWidth>
                <drawText>false</drawText>
                <font>
                    <name>Arial</name>
                    <style>BOLD</style>
                    <size>48</size>
                </font>
                <textColor>black</textColor>
            </item>
            <item>
                <x>20</x>
                <y>110</y>
                <width>752</width>
                <height>480</height>
                <type>rectangle</type>
            </item>
            <item>
                <x>30</x>
                <y>120</y>
                <width>742</width>
                <height>470</height>
                <type>map</type>
                <name>mainMap</name>
                <layers>
                    <layer>
                        <layertype>layer</layertype>
                        <file>${new File("src/test/resources/states.shp").absolutePath}</file>
                    </layer>
                </layers>
            </item>
            <item>
                <x>30</x>
                <y>490</y>
                <width>100</width>
                <height>90</height>
                <type>overViewMap</type>
                <linkedMap>mainMap</linkedMap>
                <layers>
                    <layer>
                        <layertype>raster</layertype>
                        <source>${new File("src/test/resources/raster.tif").absolutePath}</source>
                    </layer>
                </layers>
            </item>
            <item>
                <x>150</x>
                <y>490</y>
                <width>100</width>
                <height>90</height>
                <type>overViewMap</type>
                <linkedMap>mainMap</linkedMap>
                <zoomIntoBounds>true</zoomIntoBounds>
                <scaleFactor>3.0</scaleFactor>
                <layers>
                    <layer>
                        <layertype>raster</layertype>
                        <source>${new File("src/test/resources/raster.tif").absolutePath}</source>
                    </layer>
                </layers>
            </item>
            <item>
                <x>460</x>
                <y>120</y>
                <width>300</width>
                <height>200</height>
                <type>table</type>
                <columns>
                    <column>ID</column>
                    <column>Name</column>
                </columns>
                <rows>
                    <row><ID>1</ID><Name>One</Name></row>
                    <row><ID>2</ID><Name>Two</Name></row>
                    <row><ID>3</ID><Name>Three</Name></row>
                </rows>
            </item>
            <item>
                <x>640</x>
                <y>500</y>
                <width>120</width>
                <height>80</height>
                <type>legend</type>
                <map>mainMap</map>
                <backgroundColor>white</backgroundColor>
                <title>Legend</title>
                <titleFont>
                    <name>Arial</name>
                    <style>bold</style>
                    <size>18</size>
                </titleFont>
                <titleColor>black</titleColor>
                <textFont>
                    <name>Arial</name>
                    <style>plain</style>
                    <size>12</size>
                </textFont>
                <textColor>black</textColor>
                <legendEntryWidth>50</legendEntryWidth>
                <legendEntryHeight>30</legendEntryHeight>
                <gapBetweenEntries>10</gapBetweenEntries>
                <numberFormat>#.##</numberFormat>
            </item>
            <item>
                <x>150</x>
                <y>85</y>
                <width>200</width>
                <height>10</height>
                <type>scaleText</type>
                <map>mainMap</map>
                <font>
                    <name>Arial</name>
                    <style>italic</style>
                    <size>18</size>
                </font>
                <color>black</color>
                <horizontalAlign>left</horizontalAlign>
                <verticalAlign>bottom</verticalAlign>
                <format>#</format>
                <prefixText>Scale :</prefixText>
            </item>
            <item>
                <x>50</x>
                <y>125</y>
                <width>200</width>
                <height>20</height>
                <type>scaleBar</type>
                <map>mainMap</map>
                <strokeColor>black</strokeColor>
                <fillColor>white</fillColor>
                <strokeWidth>1</strokeWidth>
                <font>
                    <name>Arial</name>
                    <style>italic</style>
                    <size>12</size>
                </font>
                <border>1</border>
                <units>metric</units>
            </item>
          </items>
        </carto>"""
        CartoReader cartoReader = new XmlCartoReader()
        CartoBuilder cartoBuilder = cartoReader.read(xml)
        boolean saveToTarget = false
        File file = saveToTarget ? new File("target/carto_xml.png"): File.createTempFile("carto_xml","png")
        file.withOutputStream { OutputStream outputStream ->
            cartoBuilder.build(outputStream)
        }
    }

}
